# Generated by Django 2.2 on 2019-05-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='diff',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')], null=True),
        ),
    ]
