# Generated by Django 2.2 on 2019-04-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20190423_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_recipe',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='add_recipe',
            name='description',
            field=models.TextField(help_text='Описание рецепта'),
        ),
    ]
