# Generated by Django 2.2.1 on 2019-05-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20190528_0013'),
        ('recipes', '0002_recipe_views'),
    ]

    operations = [
    ]
