# Generated by Django 2.2.1 on 2019-05-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20190526_1506'),
        ('recipes', '0004_auto_20190526_1232'),
    ]

    operations = [
    ]
