# Generated by Django 2.2 on 2019-05-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20190425_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_recipe',
            name='diff',
            field=models.CharField(choices=[('Very easy', '1'), ('Easy', '2'), ('Normal', '3'), ('Hard', '4'), ('Very hard', '5')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='add_recipe',
            name='image',
            field=models.ImageField(height_field=100, upload_to='articles/', width_field=100),
        ),
    ]
