# Generated by Django 2.2 on 2019-05-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20190512_0925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_recipe',
            new_name='Recipe',
        ),
    ]
