# Generated by Django 2.2 on 2019-05-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_merge_20190527_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
