# Generated by Django 2.2 on 2019-05-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20190522_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_recipe',
            name='dislikes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='add_recipe',
            name='likes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='add_recipe',
            name='diff',
            field=models.CharField(choices=[('Очень легко', 'Очень легко'), ('Легко', 'Легко'), ('Нормально', 'Нормально'), ('Сложно', 'Сложно'), ('Очень сложно', 'Очень сложно')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='add_recipe',
            name='image',
            field=models.ImageField(upload_to='articles/'),
        ),
    ]
