# Generated by Django 2.2 on 2019-05-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20190522_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_recipe',
            name='rat',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True),
        ),
        migrations.AlterField(
            model_name='add_recipe',
            name='diff',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')], null=True),
        ),
    ]
